# Generated by Django 5.0.7 on 2024-07-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic', models.CharField(max_length=100)),
                ('russian', models.CharField(max_length=100)),
                ('transcription', models.CharField(max_length=100, null=True)),
                ('examples', models.IntegerField(null=True, verbose_name=250)),
            ],
        ),
    ]
