# Generated by Django 5.0.7 on 2024-07-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic', models.CharField(max_length=100)),
                ('russian', models.CharField(max_length=100)),
                ('transcription', models.CharField(max_length=100, blank=True, null=True)),
                ('examples', models.CharField(max_length=250, blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
