# Generated by Django 5.0.7 on 2024-07-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
