# Generated by Django 5.0.7 on 2024-07-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='examples',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='transcription',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
